name: aquarium_idle_game
description: A virtual aquarium idle game.

environment:
  sdk: '^3.7.0'  # Angepasst an deine aktuelle Dart-Version

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  lottie: ^3.1.2
  provider: ^6.1.2  # Füge Provider hinzu
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  rxdart: ^0.28.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/